### ISSUE TITLE
Upgrade to 0.25

### ISSUE THREAD

**Issue by garethrees** [mysociety/dirittodisapere-theme#103]

**Comment by garethrees** [comment]
Current version is `0.24.1.10`

**Comment by clacesarano** [comment]
I just translated the new strings for 0.26 release. Can you upgrade Chiedi to that version?

**Comment by garethrees** [comment]
Thanks @clacesarano! 🎉  I've created a ticket for this (#104) so we'll get it scheduled in when we can. Cheers!

**Comment by lizconlan** [comment]
ToDo:
- [ ] look at frontage caching
- [ ] reimplement blog overrides based on AskTheEU theme

**Comment by lizconlan** [comment]
Suggestion that we switch the locale to it_IT [space left blank for inclusion of new ticket number]
