### ISSUE TITLE
Change the locale from it to it_IT

### ISSUE THREAD

**Issue by lizconlan** [mysociety/dirittodisapere-theme#106]
This will allow us to use the country specific locale for dirittodisapere and use the more general Italian locale for sites such as AskTheEU

**Comment by lizconlan** [comment]
ToDo:
 - [ ] add `it_IT` to dirittodisapere-theme in Transifex
 - [ ] duplicate the translations from the `it` locale
 - [ ] update the `PublicBody` data to work with the new locale
 - [ ] switch the theme settings (and test carefully)
 - [ ] talk to the site team about the changes to Transifex
 - [ ] copy the Transifex team settings to the new language and remove old `it` locale from the theme

**Comment by lizconlan** [comment]
New plan, targeting #104 instead

**Comment by lizconlan** [comment]
There's more to this one, reopening

**Comment by lizconlan** [comment]
2 problems with the switchover...

1. the database did not like the `it_IT` locale so I missed ... something
2. the translation fix for "list public bodies" may not have been duplicated into the it_IT translations in Transifex... need to check before redeploying (might be a theme level translation now I come to think of it)

**Comment by lizconlan** [comment]
Actual - truncated - error:

```
An ActiveRecord::StatementInvalid occurred in public_body#list:

  PG::UndefinedObject: ERROR:  collation "it_IT" for encoding "SQL_ASCII" does not exist
LINE 2: ...OALESCE(current_locale.name, default_locale.name) COLLATE "i...
```

Collation vs encoding problem that needs to be resolved. it_IT looks like this:

```
  collname  | collnamespace | collowner | collencoding | collcollate | collctype
------------+---------------+-----------+--------------+-------------+------------
 it_IT      |            11 |        10 |            6 | it_IT.utf8  | it_IT.utf8
 it_IT.utf8 |            11 |        10 |            6 | it_IT.utf8  | it_IT.utf8
```

en_GB like this:
```
    collname    | collnamespace | collowner | collencoding |  collcollate   |   collctype
----------------+---------------+-----------+--------------+----------------+----------------
 en_GB          |            11 |        10 |            6 | en_GB.utf8     | en_GB.utf8
 en_GB          |            11 |        10 |            8 | en_GB          | en_GB
 en_GB.iso88591 |            11 |        10 |            8 | en_GB.iso88591 | en_GB.iso88591
 en_GB.utf8     |            11 |        10 |            6 | en_GB.utf8     | en_GB.utf8
```

The `collencoding` column may prove worthy of note (or another red herring, of course).

**Comment by lizconlan** [comment]
Ah, it may be that `it` is being used as the "collation" in the current site which is _not_ supported by the database meaning we run the query that's failing with `it_IT` without the `COLLATE` part of the statement.

public_body_controller.rb:165-169
```rb
if DatabaseCollation.supports?(underscore_locale)
  select_sql = %Q(SELECT public_bodies.*, COALESCE(current_locale.name, default_locale.name) COLLATE "#{ underscore_locale }" AS display_name)
else
  select_sql = %Q(SELECT public_bodies.*, COALESCE(current_locale.name, default_locale.name) AS display_name)
end
```

**Comment by garethrees** [comment]
Did you investigate whether databases encoded in `SQL_ASCII` support the use of `COLLATE`?

**Comment by lizconlan** [comment]
> Did you investigate whether databases encoded in SQL_ASCII support the use of COLLATE?

It supports COLLATE as running the following works...

```
SELECT name FROM public_body_translations ORDER BY name COLLATE "C" LIMIT 4;
```

I think it's quite likely we've not been using it. The vast majority our collations have a `collencoding` ("Encoding in which the collation is applicable") of 6 (UTF8) with a couple that are 8 (LATIN1) [1].

Some possible "fixes" in my mind...

1. alter `DatabaseCollation.supports?` so that it checks for a compatible db locale - this currently performs an existence check on the locale name only, the encoding[2] is not taken into account
2. try to create a locale with a `collencoding` of `0` (SQL_ASCII) and see if this fixes the problem - assuming that a multibyte collation makes sense for ASCII encoding but the documentation on encoding and collation is poor (or at least not easily findable) so this may be the only way to find out
3. emergency cheat - fall back to a collation of 'C' for ordering as it at least [differentiates between accented and non-accented letters](http://dba.stackexchange.com/a/94972) but won't respect language-specific rules around punctuation etc

Aside - web documentation considered slightly unhelpful as there has been a change between how the collation information is stored between Postgres 8 and Postgres 9 so a lot of the available information is out of date

[1] `SELECT pg_encoding_to_char(6);` or for a bonus point `SELECT i, pg_encoding_to_char(i) FROM generate_series(0,50) AS i;` to see the complete list
[2] `SHOW SERVER_ENCODING;`

**Comment by garethrees** [comment]
> Did you investigate whether databases encoded in SQL_ASCII support the use of COLLATE

Soz, should have been more explicit

> [17:27:37]  <matthew>	I think only default, C, POSIX collations work on SQL_ASCII

A better question to ask would be "When a database is encoded with `SQL_ASCII`, does `COLLATE` support anything other than default, C and POSIX?"

**Comment by lizconlan** [comment]
From what I can gather, `it_IT` is a `C` compatible collation

**Comment by lizconlan** [comment]
What's holding this up is that we're doing a naive lookup on collation availability in the `DatabaseCollation` class. Ticket to improve this opened against core https://github.com/mysociety/alaveteli/issues/3683

Setting this aside for now

**Comment by lizconlan** [comment]
Switched over without incident this time, giving it some time in Awaiting Review before closing in case there are any problems on the site that I've overlooked

**Comment by lizconlan** [comment]
no errors over the weekend, closing
