### ISSUE TITLE
www redirect

### ISSUE THREAD

**Issue by dracos** [mysociety/dirittodisapere-theme#95]
After seeing someone complain on Twitter, I've set up www to redirect to chiedi; I obtained a LE cert for the www, because for some reason the main cert doesn't have the standard www alt.
I wasn't sure if the site was deployable, so just added it manually to webserver; it should be fine through a deploy too, this is just a note that can be closed once that's checked.

**Comment by garethrees** [comment]
Thanks!

**Comment by garethrees** [comment]
Looks fine to me
