### ISSUE TITLE
Fix a link

### ISSUE THREAD

**Issue by clacesarano** [mysociety/dirittodisapere-theme#98]
The menu item "Non abbiamo inserito una pubblica amministrazione?" (= "Are we missing a publi authority") in the left column of "Lista amministrazioni" (= "View authorities") should direct to this page https://chiedi.dirittodisapere.it/change_request/new

**Comment by clacesarano** [comment]
a user reported us an error with the captcha of this page Add authority page. is it related to the changes you are currently making?
![captcha](https://cloud.githubusercontent.com/assets/13468021/20171424/db8d8966-a730-11e6-8283-5b941a01e47b.jpg)

**Comment by lizconlan** [comment]
Hi Claudio

Sorry about that, it should be working again now!

Regards,
Liz
--
*Developer*
mySociety | mysociety.org <https://www.mysociety.org/>

**Comment by clacesarano** [comment]
Thanks Liz,

Best,

Claudio

**Comment by lizconlan** [comment]
If I've read this properly then this is supposed to link to a specific section of the `/help/requesting` page which has a link to the form (and to Contact Us for adding lots of things). It looks to me as though this should be https://chiedi.dirittodisapere.it/help/requesting#scelta_pa in which case fixing it will just be changing "#scelta_pa" to the English #missing_body

I'll open a new ticket to review the anchor link names in the help pages to see if any required anchors have been inadvertently translated
